- name: bundle install
  command: chdir="{{ build_path }}" bundle install --path='{{ shared_path }}/vendor/bundle' --gemfile='./Gemfile' --without development test --deployment --binstubs='./bin'
  register: bundler
  changed_when: "'Installing' in bundler or 'Updating' in bundler or 'upgrade' in bundler"
  environment:
    RAILS_ENV: "{{ rails_env }}"

- name: check schema for diffs
  diff:
    paths: "{{ migrate_diff_paths }}"
  when: migrate
  register: rails_schema

- name: migrate the database
  command: chdir="{{ build_path }}" bundle exec rake db:migrate
  environment:
    RAILS_ENV: "{{ rails_env }}"
  when: migrate and (force_migrate or rails_schema|changed)

#- name: check assets for diffs
  #diff:
    #paths: "{{ asset_precompile_diff_paths }}"
  #when: compile_assets
  #register: assets

- name: precompile asset files if necessary
  command: chdir="{{ build_path }}" bundle exec rake assets:precompile
  environment:
    RAILS_ENV: "{{ rails_env }}"
  when: compile_assets
    #and (assets|changed or force_asset_compilation)
